In [2]:
import torch
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [8]:
x.numel()
x.shape
X = x.reshape(3, 4)
# print(X)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
torch.zeros((2,3,4))
torch.ones((2,3,4))
torch.randn(3,4)

tensor([[-2.5327, -0.9570,  0.7372, -0.4051],
        [-0.3025, -2.4663, -0.3536, -0.3727],
        [-0.8430,  1.7255, -1.0765, -0.9234]])

In [15]:
X[:2, :] = 12
print(X)

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


In [16]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [27]:
a = torch.arange(6).reshape((3, 2))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 1]]))

In [28]:
print(a + b)

tensor([[0, 2],
        [2, 4],
        [4, 6]])


In [30]:
Y = torch.tensor([[2.0,1, 4, 3], [1,2,3,4], [4,3,2,1]])
before = id(Y)
Y[:] = Y + X
id(Y) == before

True

In [ ]:
A = X.numpy()
B = torch.from_numpy(A)
type

In [31]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0,1, 4, 3], [1,2,3,4], [4,3,2,1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [35]:
print(X > Y)

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
