In [13]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [14]:
x.requires_grad_(True)
# x.grad

tensor([0., 1., 2., 3.], requires_grad=True)

In [15]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [16]:
y.backward()
print(x.grad)

tensor([ 0.,  4.,  8., 12.])


In [17]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [18]:
x.grad.zero_()
y = x * x
y.backward(gradient=torch.ones(len(x)))
x.grad

tensor([0., 2., 4., 6.])

In [35]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u


tensor([True, True, True, True])

In [21]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [40]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d / a

tensor(1024.)